kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  podSubnet: 10.212.0.0/16
  serviceSubnet: 10.112.0.0/16
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
